language: php
sudo: required
dist: trusty

php:
  - 5.6

install:
  # Remove xdebug to make composer faster.

  - phpenv config-rm xdebug.ini
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"

  # Install PHP_CodeSniffer and Drupal config
  - composer global require drupal/coder

  - phpcs --config-set installed_paths ~/.config/composer/vendor/drupal/coder/coder_sniffer

before_script:
  # This slows things down but it ensures all remote branches are fetched.
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script: ./travis.sh

notifications:
  email:
    - davic@ciandt.com